app:
  currency: GBP
  price:
    one-segment: 5
    two-segments: 7
    three-segments: 10

spring:
  application:
    name: ticket-to-ride
  datasource:
    url: jdbc:postgresql://localhost:5432/ticket_to_ride_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true